### PR TITLE
Add test for loading multiple vllm models at once

### PR DESCRIPTION
**Pull request by rmccorm4**
Tests https://github.com/triton-inference-server/core/pull/274

### CODE REVIEW

**Review by oandreeva-nv — APPROVED** [review]
LGTM

**Comment by rmccorm4** [comment]
Need to change default merge settings to squash in this repo btw

**Comment by jbkyang-nvi** [comment]
@oandreeva-nv ? ^

**Comment by oandreeva-nv** [comment]
@jbkyang-nvi should be already updated

**Comment by oandreeva-nv** [comment]
image

**Pull request merged**
